// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	AddBankAccountBalance(ctx context.Context, arg AddBankAccountBalanceParams) (BankAccount, error)
	CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (BankAccount, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBankAccount(ctx context.Context, id int64) error
	GetBankAccount(ctx context.Context, id int64) (BankAccount, error)
	GetBankAccountForUpdate(ctx context.Context, id int64) (BankAccount, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListBankAccounts(ctx context.Context, arg ListBankAccountsParams) ([]BankAccount, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	UpdateBankAccount(ctx context.Context, arg UpdateBankAccountParams) (BankAccount, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
